version: "3.8"

services:
  mysqldb:
    image: mysql:8.0.29-debian
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    volumes:
      - db:/var/lib/mysql

  app:
    depends_on:
      - mysqldb
    image: registry.gitlab.com/vasudevan.ajay/spring-mysql-reactive/reactive-mysql:1.0.1
    restart: on-failure
    env_file: ./.env
    ports:
      - $SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.r2dbc.url"  : "r2dbc:mysql://mysqldb:3306/payroll",
        "spring.r2dbc.username" : "root",
        "spring.r2dbc.password" : "mysqlpassword"
      }'
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true

volumes:
  db: